lsst/resources

- doc/changes/DM-32482.feature.rst
- python/lsst/resources/__init__.py
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/file.py
- python/lsst/resources/packageresource.py
- tests/test_uri.py
> DM-32842: `open` and miscelleneous minor improvements

- python/lsst/resources/http.py
- tests/test_uri.py
Unit tests executed in my development environment passed. Could not run Jenkins.
> DM-33360: Improve performance of https as_local() method

- .github/workflows/mypy.yaml
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/tests.py
- setup.cfg
> DM-32250: Update setup.cfg to install py.typed file.

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/docstyle.yaml
- .github/workflows/formatting.yaml
- .github/workflows/lint.yaml
- .github/workflows/mypy.yaml
- python/lsst/resources/s3.py
Python 3.10 mypy found additional problems.
> DM-34980: Fix type annotation problems in S3

- .github/workflows/docstyle.yaml
- .github/workflows/formatting.yaml
- .github/workflows/lint.yaml
- .github/workflows/mypy.yaml
- types.txt
> switch to reusable workflows

- .github/workflows/build.yaml
- LICENSE
- requirements.txt
- setup.cfg
> DM-35047: Add uploading build to PyPi

- .github/workflows/build.yaml
> DM-35191: Add test matrix for python versions

- types.txt
> DM-35199: Fix python package names

- .github/workflows/build.yaml
- requirements.txt
> DM-35220: Use python dependencies from github

- doc/changes/DM-35446.misc.rst
- pyproject.toml
- python/lsst/resources/file.py
> DM-35446: Follow directory symlinks when walking

- doc/changes/DM-36799.misc.rst
- python/lsst/resources/http.py
> allow_redirects=True for head requests

- python/lsst/resources/http.py
> DM-37259: Accept 200 response code for PUT requests

- python/lsst/resources/__init__.py
- python/lsst/resources/_resourceHandles/__init__.py
- python/lsst/resources/_resourceHandles/_baseResourceHandle.py
- python/lsst/resources/_resourceHandles/_fileResourceHandle.py
- python/lsst/resources/_resourceHandles/_httpResourceHandle.py
- python/lsst/resources/_resourceHandles/_s3ResourceHandle.py
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/file.py
- python/lsst/resources/gs.py
- python/lsst/resources/http.py
- python/lsst/resources/packageresource.py
- python/lsst/resources/s3.py
- python/lsst/resources/s3utils.py
- tests/test_http.py
- tests/test_s3.py
Introduce a handle like interface to ResourcePaths. This is just a draft PR for discussion, and will be updated with new content.
> DM-33682: Introduce ResourceHandles

- .github/workflows/build.yaml
- .pre-commit-config.yaml
- doc/changes/DM-36412.misc.rst
- doc/changes/DM-36799.misc.rst
- doc/lsst.resources/CHANGES.rst
- pyproject.toml
- python/lsst/resources/tests.py
- tests/test_http.py
> DM-38065: V25 release notes

- python/lsst/resources/http.py
- tests/test_http.py
> DM-38156: Improve persistent connection handling for HttpResourcePath class

- .github/workflows/build.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/changes/DM-39791.removal.md
- pyproject.toml
- python/lsst/resources/_resourceHandles/_baseResourceHandle.py
- python/lsst/resources/_resourceHandles/_fileResourceHandle.py
- python/lsst/resources/_resourceHandles/_httpResourceHandle.py
- python/lsst/resources/_resourceHandles/_s3ResourceHandle.py
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/file.py
- python/lsst/resources/gs.py
- python/lsst/resources/http.py
- python/lsst/resources/location.py
- python/lsst/resources/mem.py
- python/lsst/resources/s3.py
- python/lsst/resources/s3utils.py
- python/lsst/resources/schemeless.py
- python/lsst/resources/tests.py
- python/lsst/resources/utils.py
- tests/test_file.py
- tests/test_gs.py
- tests/test_http.py
- tests/test_location.py
- tests/test_mem.py
- tests/test_resource.py
- tests/test_s3.py
- tests/test_s3utils.py
> DM-39791: Modernize python and add ruff configuration

- .github/workflows/build.yaml
- pyproject.toml
> DM-39857: Remove usage of pytest-flake8 in tests

- .pre-commit-config.yaml
- doc/changes/DM-40762.bugfix.rst
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/http.py
- python/lsst/resources/s3.py
- python/lsst/resources/s3utils.py
> DM-40762: Force S3 client to be created before threading in mexists

- doc/changes/DM-33528.feature.rst
- doc/changes/DM-35695.bugfix.rst
- doc/changes/DM-37439.bugfix.md
- doc/changes/DM-38492.misc.rst
- doc/changes/DM-38552.feature.rst
- doc/changes/DM-38589.bugfix.rst
- doc/changes/DM-38742.feature.rst
- doc/changes/DM-39044.feature.rst
- doc/changes/DM-39791.removal.md
- doc/changes/DM-40762.bugfix.rst
- doc/lsst.resources/CHANGES.rst
- pyproject.toml
- requirements.txt
> DM-40883: v26 release notes

- .github/workflows/build_docs.yaml
- doc/changes/DM-33528.feature.rst
- doc/changes/DM-35695.bugfix.rst
- doc/changes/DM-37439.bugfix.md
- doc/changes/DM-38492.misc.rst
- doc/changes/DM-38552.feature.rst
- doc/changes/DM-38589.bugfix.rst
- doc/changes/DM-38742.feature.rst
- doc/changes/DM-39044.feature.rst
- doc/changes/DM-39791.removal.md
- doc/changes/DM-40762.bugfix.rst
- doc/lsst.resources/CHANGES.rst
> DM-40883 (main): v26 release notes

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .pre-commit-config.yaml
- pyproject.toml
> DM-41904: Enable python 3.12

- requirements.txt
> DM-43150: Fix moto regression in S3 tests

- doc/changes/DM-44486.bugfix.rst
- python/lsst/resources/_resourceHandles/_httpResourceHandle.py
- python/lsst/resources/_resourceHandles/_s3ResourceHandle.py
- python/lsst/resources/s3.py
- python/lsst/resources/tests.py
> DM-44486: Fix SEEK_END for HTTP and S3 handles

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/do_not_merge.yaml
- .github/workflows/docstyle.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/changes/DM-41112.bugfix.rst
- doc/changes/DM-41547.bugfix.rst
- doc/changes/DM-41879.feature.rst
- doc/changes/DM-41879.removal.rst
- doc/changes/DM-42306.feature.rst
- doc/changes/DM-42306.misc.rst
- doc/changes/DM-42306.perf.md
- doc/changes/DM-42522.bugfix.rst
- doc/changes/DM-42704.feature.rst
- doc/changes/DM-43739.bugfix.md
- doc/changes/PREOPS-4765.feature.rst
- doc/lsst.resources/CHANGES.rst
- pyproject.toml
- requirements.txt
> DM-44569: v27 release notes (on branch)

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/codeql-analysis.yml
- .github/workflows/do_not_merge.yaml
- .github/workflows/docstyle.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/changes/DM-41112.bugfix.rst
- doc/changes/DM-41547.bugfix.rst
- doc/changes/DM-41879.feature.rst
- doc/changes/DM-41879.removal.rst
- doc/changes/DM-42306.feature.rst
- doc/changes/DM-42306.misc.rst
- doc/changes/DM-42306.perf.md
- doc/changes/DM-42522.bugfix.rst
- doc/changes/DM-42704.feature.rst
- doc/changes/DM-43739.bugfix.md
- doc/changes/PREOPS-4765.feature.rst
- doc/lsst.resources/CHANGES.rst
- pyproject.toml
- python/lsst/resources/packageresource.py
- requirements.txt
> DM-44569: V27 release notes

- .github/workflows/build.yaml
- doc/changes/DM-44547.feature.rst
- doc/conf.py
- mypy.ini
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/file.py
- python/lsst/resources/packageresource.py
- python/lsst/resources/s3.py
- python/lsst/resources/s3utils.py
- python/lsst/resources/tests.py
- tests/test_resource.py
- tests/test_s3.py
> DM-44547: Add fsspec constructor

- doc/changes/DM-44486.bugfix.rst
- doc/changes/DM-44547.feature.rst
- doc/changes/DM-44762.feature.rst
- doc/changes/DM-44840.bugfix.md
- doc/changes/DM-45732.misc.rst
- doc/changes/DM-46139.feature.md
- doc/lsst.resources/CHANGES.rst
- requirements.txt
> DM-47673: v28 release notes

- .github/workflows/build.yaml
> Add codecov test report upload

- .pre-commit-config.yaml
- doc/changes/DM-46776.feature.rst
- doc/lsst.resources/CHANGES.rst
- pyproject.toml
> DM-49674: v29 release notes

- doc/changes/DM-49786.misc.rst
- python/lsst/resources/_resourceHandles/_httpResourceHandle.py
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/http.py
- tests/test_http.py
Currently become http internally.
> DM-49786: Add dav[s] scheme stubs

- python/lsst/resources/http.py
Change to a single webdav test case using "dav" scheme.
> DM-49786 (hotfix): Fix some other dav vs https issues

- python/lsst/resources/_resourceHandles/_httpResourceHandle.py
> DM-50506: Close connection to the backend server in partial reads

- doc/changes/DM-50074.misc.rst
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/http.py
- python/lsst/resources/s3.py
- python/lsst/resources/s3utils.py
- python/lsst/resources/tests.py
- python/lsst/resources/utils.py
- tests/test_file.py
- tests/test_http.py
- tests/test_s3.py
> DM-50074: Set pool size to number of specified workers (default 10)

- python/lsst/resources/s3utils.py
> DM-50645: Force S3 to always have at least 10 connections

- doc/changes/DM-50724.feature.rst
- doc/conf.py
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/s3.py
- python/lsst/resources/tests.py
> DM-50724: Add ResourcePath.mremove API

- doc/changes/DM-49784.feature.rst
- doc/lsst.resources/dav.rst
- doc/lsst.resources/index.rst
- mypy.ini
- python/lsst/resources/_resourceHandles/_davResourceHandle.py
- python/lsst/resources/_resourcePath.py
- python/lsst/resources/dav.py
- python/lsst/resources/davutils.py
- python/lsst/resources/http.py
- tests/test_dav.py
- tests/test_http.py
- types.txt
> DM-49784: Add specialized support for davs:// scheme

- python/lsst/resources/s3.py
> DM-50857: Add timer around s3 bulk delete

- python/lsst/resources/s3.py
> DM-51303: Add missing f to string

- .github/workflows/build_docs.yaml
- doc/changes/DM-31824.feature.rst
- doc/changes/DM-49784.feature.rst
- doc/changes/DM-49786.misc.rst
- doc/changes/DM-50074.misc.rst
- doc/changes/DM-50724.feature.rst
- doc/changes/DM-51087.misc.rst
- doc/lsst.resources/CHANGES.rst
- requirements.txt
> DM-51073 (v29.1): v29.1 release notes

- .github/workflows/build_docs.yaml
- doc/changes/DM-31824.feature.rst
- doc/changes/DM-49784.feature.rst
- doc/changes/DM-49786.misc.rst
- doc/changes/DM-50074.misc.rst
- doc/changes/DM-50724.feature.rst
- doc/changes/DM-51087.misc.rst
- doc/lsst.resources/CHANGES.rst
> DM-51073: v29.1 release notes

- python/lsst/resources/_resourcePath.py
- python/lsst/resources/dav.py
- python/lsst/resources/file.py
- python/lsst/resources/gs.py
- python/lsst/resources/http.py
- python/lsst/resources/mem.py
- python/lsst/resources/s3.py
- tests/test_dav.py
- tests/test_http.py
- tests/test_location.py
> DM-51421: Reorganize as_local to avoid leaving temp file around

- .github/workflows/build_docs.yaml
- doc/changes/DM-51540.bugfix.md
- python/lsst/resources/file.py
> DM-51540: Avoid race condition in no-overwrite copies.

- python/lsst/resources/http.py
- tests/test_http.py
Attach "extra" authorization headers provided by the user to the fsspec instance created by `HttpResourcePath.to_fsspec()`.  This is needed to support the Butler setup at the CADC IDAC, which uses an HTTP datastore that requires authentication headers.
> DM-52021: Include extra HTTP headers when creating fsspec
